name: CI

on:
  pull_request:
    paths-ignore:
      - .gitignore
      - README.md
  push:
    paths-ignore:
      - .gitignore
      - README.md

jobs:
  tests:
    name: Run Tests (Ruby ${{ matrix.ruby }}, ActiveModel ${{ matrix.rails }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        exclude:
          - rails: 7.2
            ruby: 2.7
          - rails: 7.2
            ruby: 3.0
          - rails: 8.0
            ruby: 2.7
          - rails: 8.0
            ruby: 3.0
          - rails: 8.0
            ruby: 3.1
        rails: ['6.1', '7.0', '7.1', '7.2', '8.0']
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3', '3.4']
    env:
      BUNDLE_GEMFILE: gemfiles/am_${{ matrix.rails }}.gemfile
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Run Tests
        run: bundle exec rake
