name: CI

on:
  pull_request:
    paths-ignore:
      - .gitignore
      - README.md
  push:
    paths-ignore:
      - .gitignore
      - README.md

jobs:
  tests:
    name: Run Tests (Ruby ${{ matrix.ruby }}, ActiveModel ${{ matrix.rails }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rails: ['6.1', '7.0']
        ruby: ['2.7', '3.0', '3.1', '3.2']
    env:
      BUNDLE_GEMFILE: gemfiles/am_${{ matrix.rails }}.gemfile
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Run Tests
        run: bundle exec rake
